export const transcriptData = [
    // { time: 2-7, text: "yes who's hungry more adventurous guests" },
    // { time: 6-7, text: "of course can opt for our jungle River" },
    // { time: 8-7, text: "Cruise or for a closeup look at our" },
    { time: 10-7, text: "Majestic none of these attractions are" },
    { time: 12-7, text: "ready yet of course but the park will" },
    { time: 14-7, text: "open with the basic tour you're about to" },
    { time: 16-7, text: "take and then other rides will come" },
    { time: 18-7, text: "online 6 or 12 months after that" },
    { time: 20-7, text: "absolutely spectacular design spared no" },
    { time: 23-7, text: "expense and we can charge anything we" },
    { time: 25-7, text: "want 2,000 a day 10,000 a day and people" },
    { time: 27-7, text: "will pay it and then there's the" },
    { time: 29-7, text: "merchandise" },
    { time: 30-7, text: "I can" },
    { time: 31-7, text: "person this park was not built to cater" },
    { time: 33-7, text: "only for the super rich everyone in the" },
    { time: 36-7, text: "world has the right to enjoy these" },
    { time: 38-7, text: "animals sure they will what we'll have a" },
    { time: 41-7, text: "a coupon day or" },
    { time: 44-7, text: "something" },
    { time: 46-7, text: "yes gee the lack of humility before" },
    { time: 49-7, text: "nature that's being displayed here um" },
    { time: 52-7, text: "staggers me well thank you Dr Malcolm" },
    { time: 55-7, text: "but I think things are a little bit" },
    { time: 56-7, text: "different than you and I had feared yeah" },
    { time: 57-7, text: "I know they're a lot worse now wait a" },
    { time: 59-7, text: "second now we haven't even seen the part" },
    { time: 63-7, text: "Don let him talk there's no reason I no" },
    { time: 65-7, text: "I want to hear a riew point I really do" },
    { time: 67-7, text: "yeah don't you see the danger uh John" },
    { time: 71-7, text: "inherent uh in what you're doing here" },
    { time: 73-7, text: "genetic power is the most awesome Force" },
    { time: 74-7, text: "the planet's ever seen but you wield it" },
    { time: 76-7, text: "like a a kid that's found his dad's gun" },
    { time: 78-7, text: "it's hardly appropriate to start hurling" },
    { time: 80-7, text: "generalizations if I may um I'll tell" },
    { time: 83-7, text: "you the problem with the scientific" },
    { time: 84-7, text: "power that you're that you're using here" },
    { time: 86-7, text: "uh it didn't require any discipline to" },
    { time: 88-7, text: "attain" },
    { time: 88-7, text: "it you know you read what others had" },
    { time: 91-7, text: "done and you and you took the next step" },
    { time: 93-7, text: "you didn't earn the knowledge for" },
    { time: 94-7, text: "yourselves so you don't take any" },
    { time: 97-7, text: "responsibility for it you stood on the" },
    { time: 100-7, text: "shoulders of geniuses uh to accomplish" },
    { time: 102-7, text: "something as fast as you could and" },
    { time: 103-7, text: "before you even knew what you had you" },
    { time: 105-7, text: "you patented it and packaged it and" },
    { time: 108-7, text: "slapped it on a plastic lunch boox and" },
    { time: 110-7, text: "now you're selling it you want to sell" },
    { time: 111-7, text: "it" },
    { time: 112-7, text: "well I I don't think you're giving us" },
    { time: 114-7, text: "our due credit our scientists have done" },
    { time: 117-7, text: "things which nobody's ever done before" },
    { time: 119-7, text: "yeah yeah but your scientists were so" },
    { time: 121-7, text: "preoccupied with whether or not they" },
    { time: 122-7, text: "could they didn't stop to think if they" },
    { time: 123-7, text: "should" },
    { time: 125-7, text: "Condors Condors are on the verge of" },
    { time: 128-7, text: "Extinction if I was to no no if I was to" },
    { time: 130-7, text: "create a flock of conders on this island" },
    { time: 133-7, text: "you wouldn't have anything to say no" },
    { time: 135-7, text: "hold on this isn't this is some species" },
    { time: 136-7, text: "that was obliterated by" },
    { time: 138-7, text: "deforestation or or the building of a" },
    { time: 140-7, text: "dam dinosaurs uh uh had their shot and" },
    { time: 143-7, text: "nature selected them for" },
    { time: 146-7, text: "extinction I simply don't understand" },
    { time: 148-7, text: "this Lite attit especially from a" },
    { time: 150-7, text: "scientist I mean how can we stand in the" },
    { time: 154-7, text: "light of Discovery and and not act oh" },
    { time: 157-7, text: "what's so great about Discovery it's a" },
    { time: 158-7, text: "violent penetrative act that scars what" },
    { time: 162-7, text: "explores what you call" },
    { time: 164-7, text: "Discovery I call the rape of the natural" },
    { time: 168-7, text: "world well the question is how can you" },
    { time: 170-7, text: "know anything about an extinct ecosystem" },
    { time: 173-7, text: "and therefore how could you ever assume" },
    { time: 174-7, text: "that you can control it you have plants" },
    { time: 177-7, text: "in this building that are poisonous you" },
    { time: 179-7, text: "pick them because they look good but" },
    { time: 181-7, text: "these are aggressive living things that" },
    { time: 183-7, text: "have no idea what Sentry they're in and" },
    { time: 184-7, text: "they'll defend themselves violently if" },
    { time: 189-7, text: "necessary Dr Grant if there's one person" },
    { time: 193-7, text: "here who could appreciate what I'm" },
    { time: 194-7, text: "trying to" },
    { time: 196-7, text: "do the world has just changed so" },
    { time: 198-7, text: "radically and we're all running to catch" },
    { time: 201-7, text: "up I don't want to jump to any" },
    { time: 203-7, text: "conclusions but look dinosaurs and man" },
    { time: 207-7, text: "two species separated by 65 million" },
    { time: 210-7, text: "years of evolution just been suddenly" },
    { time: 213-7, text: "thrown back into the mix together how" },
    { time: 215-7, text: "can we possibly have the slightest idea" },
    { time: 218-7, text: "of what to" },
    { time: 219-7, text: "expect I don't believe it I don't" },
    { time: 222-7, text: "believe it you're meant to come down" },
    { time: 224-7, text: "here and defend me against these" },
    { time: 225-7, text: "characters and the only one I've got on" },
    { time: 226-7, text: "my side is the blood sucking" },
    { time: 229-7, text: "lawyer thank" },
    { time: 238-7, text: "you they're here" },
  ];
  